#/bin/env python

def build(bld):
    bld(
        target = 'NDN_Module',
        name = 'NDN_Module',
        features = 'cxx',
        source = bld.path.ant_glob(['*.cpp']),
        use = ['NDN_CXX','BOOST','Tools','Storage_Module']
        )
